# Funding options for Revenge Go
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Supported platforms:
github: [lusoris]
# patreon: revenge
# open_collective: revenge
# ko_fi: revenge
# tidelift: npm/revenge
# custom: ['https://revenge.org/donate']
