linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: unreachable-code

  gosec:
    excludes:
      - G104
      - G115
      - G304
      - G404

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint
      - unnamedResult
      - hugeParam
      - rangeValCopy
      - paramTypeCombine
      - ifElseChain

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

    - text: "weak cryptographic primitive"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
