version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
    staticcheck:
      checks:
        - "all"
        - "-QF1001"
        - "-QF1008"
        - "-ST1000"  # Package comments - not required for internal packages
        - "-ST1003"  # Naming conventions - conflicts with generated code and JSON mappings
  exclusions:
    rules:
      - path: ".*_test\\.go$"
        linters:
          - gosec
          - errcheck
          - gocritic
          - staticcheck
      - text: "weak cryptographic primitive"
        linters:
          - gosec

run:
  timeout: 5m
  tests: true
