# GoReleaser configuration
version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: jellyfin-go
    main: ./cmd/jellyfin
    binary: jellyfin-go
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.GitCommit={{.ShortCommit}}

archives:
  - id: jellyfin-go
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - docs/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: jellyfin
    name: jellyfin-go
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Jellyfin Go {{ .Tag }}

    ### Installation

    Download the binary for your platform below, or use Docker:

    ```bash
    docker pull jellyfin/jellyfin-go:{{ .Tag }}
    ```

  footer: |
    ### Full Changelog

    See [CHANGELOG.md](https://github.com/jellyfin/jellyfin-go/blob/main/CHANGELOG.md) for more details.

dockers:
  - image_templates:
      - "jellyfin/jellyfin-go:{{ .Tag }}-amd64"
      - "ghcr.io/jellyfin/jellyfin-go:{{ .Tag }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - image_templates:
      - "jellyfin/jellyfin-go:{{ .Tag }}-arm64"
      - "ghcr.io/jellyfin/jellyfin-go:{{ .Tag }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

docker_manifests:
  - name_template: jellyfin/jellyfin-go:{{ .Tag }}
    image_templates:
      - jellyfin/jellyfin-go:{{ .Tag }}-amd64
      - jellyfin/jellyfin-go:{{ .Tag }}-arm64

  - name_template: jellyfin/jellyfin-go:latest
    image_templates:
      - jellyfin/jellyfin-go:{{ .Tag }}-amd64
      - jellyfin/jellyfin-go:{{ .Tag }}-arm64

  - name_template: ghcr.io/jellyfin/jellyfin-go:{{ .Tag }}
    image_templates:
      - ghcr.io/jellyfin/jellyfin-go:{{ .Tag }}-amd64
      - ghcr.io/jellyfin/jellyfin-go:{{ .Tag }}-arm64

  - name_template: ghcr.io/jellyfin/jellyfin-go:latest
    image_templates:
      - ghcr.io/jellyfin/jellyfin-go:{{ .Tag }}-amd64
      - ghcr.io/jellyfin/jellyfin-go:{{ .Tag }}-arm64
