// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fleets.sql

package adultdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFleetExpeditions = `-- name: CountFleetExpeditions :one
SELECT COUNT(*) FROM qar.expeditions WHERE fleet_id = $1
`

func (q *Queries) CountFleetExpeditions(ctx context.Context, fleetID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFleetExpeditions, fleetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFleetVoyages = `-- name: CountFleetVoyages :one
SELECT COUNT(*) FROM qar.voyages WHERE fleet_id = $1
`

func (q *Queries) CountFleetVoyages(ctx context.Context, fleetID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFleetVoyages, fleetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFleet = `-- name: CreateFleet :one
INSERT INTO qar.fleets (
    name,
    fleet_type,
    paths,
    stashdb_endpoint,
    tpdb_enabled,
    whisparr_sync,
    auto_tag_crew,
    fingerprint_on_scan,
    owner_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, fleet_type, paths, stashdb_endpoint, tpdb_enabled, whisparr_sync, auto_tag_crew, fingerprint_on_scan, owner_user_id, created_at, updated_at
`

type CreateFleetParams struct {
	Name              string      `json:"name"`
	FleetType         string      `json:"fleetType"`
	Paths             []string    `json:"paths"`
	StashdbEndpoint   *string     `json:"stashdbEndpoint"`
	TpdbEnabled       bool        `json:"tpdbEnabled"`
	WhisparrSync      bool        `json:"whisparrSync"`
	AutoTagCrew       bool        `json:"autoTagCrew"`
	FingerprintOnScan bool        `json:"fingerprintOnScan"`
	OwnerUserID       pgtype.UUID `json:"ownerUserId"`
}

func (q *Queries) CreateFleet(ctx context.Context, arg CreateFleetParams) (QarFleet, error) {
	row := q.db.QueryRow(ctx, createFleet,
		arg.Name,
		arg.FleetType,
		arg.Paths,
		arg.StashdbEndpoint,
		arg.TpdbEnabled,
		arg.WhisparrSync,
		arg.AutoTagCrew,
		arg.FingerprintOnScan,
		arg.OwnerUserID,
	)
	var i QarFleet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FleetType,
		&i.Paths,
		&i.StashdbEndpoint,
		&i.TpdbEnabled,
		&i.WhisparrSync,
		&i.AutoTagCrew,
		&i.FingerprintOnScan,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFleet = `-- name: DeleteFleet :exec
DELETE FROM qar.fleets WHERE id = $1
`

func (q *Queries) DeleteFleet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFleet, id)
	return err
}

const getFleetByID = `-- name: GetFleetByID :one

SELECT id, name, fleet_type, paths, stashdb_endpoint, tpdb_enabled, whisparr_sync, auto_tag_crew, fingerprint_on_scan, owner_user_id, created_at, updated_at FROM qar.fleets WHERE id = $1
`

// Fleets (Libraries) - QAR obfuscated queries
func (q *Queries) GetFleetByID(ctx context.Context, id uuid.UUID) (QarFleet, error) {
	row := q.db.QueryRow(ctx, getFleetByID, id)
	var i QarFleet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FleetType,
		&i.Paths,
		&i.StashdbEndpoint,
		&i.TpdbEnabled,
		&i.WhisparrSync,
		&i.AutoTagCrew,
		&i.FingerprintOnScan,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFleetStats = `-- name: GetFleetStats :one
SELECT
    COUNT(DISTINCT e.id) AS expedition_count,
    COUNT(DISTINCT v.id) AS voyage_count,
    COALESCE(SUM(e.size_bytes), 0) + COALESCE(SUM(v.size_bytes), 0) AS total_size_bytes
FROM qar.fleets f
LEFT JOIN qar.expeditions e ON e.fleet_id = f.id
LEFT JOIN qar.voyages v ON v.fleet_id = f.id
WHERE f.id = $1
`

type GetFleetStatsRow struct {
	ExpeditionCount int64 `json:"expeditionCount"`
	VoyageCount     int64 `json:"voyageCount"`
	TotalSizeBytes  int32 `json:"totalSizeBytes"`
}

func (q *Queries) GetFleetStats(ctx context.Context, id uuid.UUID) (GetFleetStatsRow, error) {
	row := q.db.QueryRow(ctx, getFleetStats, id)
	var i GetFleetStatsRow
	err := row.Scan(&i.ExpeditionCount, &i.VoyageCount, &i.TotalSizeBytes)
	return i, err
}

const listFleets = `-- name: ListFleets :many
SELECT id, name, fleet_type, paths, stashdb_endpoint, tpdb_enabled, whisparr_sync, auto_tag_crew, fingerprint_on_scan, owner_user_id, created_at, updated_at FROM qar.fleets
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListFleetsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFleets(ctx context.Context, arg ListFleetsParams) ([]QarFleet, error) {
	rows, err := q.db.Query(ctx, listFleets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QarFleet{}
	for rows.Next() {
		var i QarFleet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FleetType,
			&i.Paths,
			&i.StashdbEndpoint,
			&i.TpdbEnabled,
			&i.WhisparrSync,
			&i.AutoTagCrew,
			&i.FingerprintOnScan,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetsByOwner = `-- name: ListFleetsByOwner :many
SELECT id, name, fleet_type, paths, stashdb_endpoint, tpdb_enabled, whisparr_sync, auto_tag_crew, fingerprint_on_scan, owner_user_id, created_at, updated_at FROM qar.fleets
WHERE owner_user_id = $1
ORDER BY name
`

func (q *Queries) ListFleetsByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]QarFleet, error) {
	rows, err := q.db.Query(ctx, listFleetsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QarFleet{}
	for rows.Next() {
		var i QarFleet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FleetType,
			&i.Paths,
			&i.StashdbEndpoint,
			&i.TpdbEnabled,
			&i.WhisparrSync,
			&i.AutoTagCrew,
			&i.FingerprintOnScan,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetsByType = `-- name: ListFleetsByType :many
SELECT id, name, fleet_type, paths, stashdb_endpoint, tpdb_enabled, whisparr_sync, auto_tag_crew, fingerprint_on_scan, owner_user_id, created_at, updated_at FROM qar.fleets
WHERE fleet_type = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListFleetsByTypeParams struct {
	FleetType string `json:"fleetType"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListFleetsByType(ctx context.Context, arg ListFleetsByTypeParams) ([]QarFleet, error) {
	rows, err := q.db.Query(ctx, listFleetsByType, arg.FleetType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QarFleet{}
	for rows.Next() {
		var i QarFleet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FleetType,
			&i.Paths,
			&i.StashdbEndpoint,
			&i.TpdbEnabled,
			&i.WhisparrSync,
			&i.AutoTagCrew,
			&i.FingerprintOnScan,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFleet = `-- name: UpdateFleet :one
UPDATE qar.fleets
SET
    name = $2,
    fleet_type = $3,
    paths = $4,
    stashdb_endpoint = $5,
    tpdb_enabled = $6,
    whisparr_sync = $7,
    auto_tag_crew = $8,
    fingerprint_on_scan = $9,
    owner_user_id = $10
WHERE id = $1
RETURNING id, name, fleet_type, paths, stashdb_endpoint, tpdb_enabled, whisparr_sync, auto_tag_crew, fingerprint_on_scan, owner_user_id, created_at, updated_at
`

type UpdateFleetParams struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	FleetType         string      `json:"fleetType"`
	Paths             []string    `json:"paths"`
	StashdbEndpoint   *string     `json:"stashdbEndpoint"`
	TpdbEnabled       bool        `json:"tpdbEnabled"`
	WhisparrSync      bool        `json:"whisparrSync"`
	AutoTagCrew       bool        `json:"autoTagCrew"`
	FingerprintOnScan bool        `json:"fingerprintOnScan"`
	OwnerUserID       pgtype.UUID `json:"ownerUserId"`
}

func (q *Queries) UpdateFleet(ctx context.Context, arg UpdateFleetParams) (QarFleet, error) {
	row := q.db.QueryRow(ctx, updateFleet,
		arg.ID,
		arg.Name,
		arg.FleetType,
		arg.Paths,
		arg.StashdbEndpoint,
		arg.TpdbEnabled,
		arg.WhisparrSync,
		arg.AutoTagCrew,
		arg.FingerprintOnScan,
		arg.OwnerUserID,
	)
	var i QarFleet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FleetType,
		&i.Paths,
		&i.StashdbEndpoint,
		&i.TpdbEnabled,
		&i.WhisparrSync,
		&i.AutoTagCrew,
		&i.FingerprintOnScan,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
