// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voyages.sql

package adultdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countVoyagesByFleet = `-- name: CountVoyagesByFleet :one
SELECT COUNT(*) FROM qar.voyages WHERE fleet_id = $1
`

func (q *Queries) CountVoyagesByFleet(ctx context.Context, fleetID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVoyagesByFleet, fleetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVoyage = `-- name: CreateVoyage :one
INSERT INTO qar.voyages (
    fleet_id,
    title,
    sort_title,
    overview,
    launch_date,
    distance,
    port_id,
    whisparr_id,
    stash_id,
    charter,
    registry,
    path,
    size_bytes,
    video_codec,
    audio_codec,
    resolution,
    oshash,
    coordinates,
    md5,
    cover_path
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
RETURNING id, title, sort_title, overview, launch_date, distance, port_id, whisparr_id, stash_id, charter, registry, path, size_bytes, video_codec, audio_codec, resolution, oshash, coordinates, md5, cover_path, created_at, updated_at, fleet_id
`

type CreateVoyageParams struct {
	FleetID     uuid.UUID   `json:"fleetId"`
	Title       string      `json:"title"`
	SortTitle   *string     `json:"sortTitle"`
	Overview    *string     `json:"overview"`
	LaunchDate  pgtype.Date `json:"launchDate"`
	Distance    *int32      `json:"distance"`
	PortID      pgtype.UUID `json:"portId"`
	WhisparrID  *int32      `json:"whisparrId"`
	StashID     *string     `json:"stashId"`
	Charter     *string     `json:"charter"`
	Registry    *string     `json:"registry"`
	Path        string      `json:"path"`
	SizeBytes   *int64      `json:"sizeBytes"`
	VideoCodec  *string     `json:"videoCodec"`
	AudioCodec  *string     `json:"audioCodec"`
	Resolution  *string     `json:"resolution"`
	Oshash      *string     `json:"oshash"`
	Coordinates *string     `json:"coordinates"`
	Md5         *string     `json:"md5"`
	CoverPath   *string     `json:"coverPath"`
}

func (q *Queries) CreateVoyage(ctx context.Context, arg CreateVoyageParams) (QarVoyage, error) {
	row := q.db.QueryRow(ctx, createVoyage,
		arg.FleetID,
		arg.Title,
		arg.SortTitle,
		arg.Overview,
		arg.LaunchDate,
		arg.Distance,
		arg.PortID,
		arg.WhisparrID,
		arg.StashID,
		arg.Charter,
		arg.Registry,
		arg.Path,
		arg.SizeBytes,
		arg.VideoCodec,
		arg.AudioCodec,
		arg.Resolution,
		arg.Oshash,
		arg.Coordinates,
		arg.Md5,
		arg.CoverPath,
	)
	var i QarVoyage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SortTitle,
		&i.Overview,
		&i.LaunchDate,
		&i.Distance,
		&i.PortID,
		&i.WhisparrID,
		&i.StashID,
		&i.Charter,
		&i.Registry,
		&i.Path,
		&i.SizeBytes,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Resolution,
		&i.Oshash,
		&i.Coordinates,
		&i.Md5,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FleetID,
	)
	return i, err
}

const deleteVoyage = `-- name: DeleteVoyage :exec
DELETE FROM qar.voyages WHERE id = $1
`

func (q *Queries) DeleteVoyage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVoyage, id)
	return err
}

const getVoyageByCharter = `-- name: GetVoyageByCharter :one
SELECT id, title, sort_title, overview, launch_date, distance, port_id, whisparr_id, stash_id, charter, registry, path, size_bytes, video_codec, audio_codec, resolution, oshash, coordinates, md5, cover_path, created_at, updated_at, fleet_id FROM qar.voyages WHERE charter = $1
`

func (q *Queries) GetVoyageByCharter(ctx context.Context, charter *string) (QarVoyage, error) {
	row := q.db.QueryRow(ctx, getVoyageByCharter, charter)
	var i QarVoyage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SortTitle,
		&i.Overview,
		&i.LaunchDate,
		&i.Distance,
		&i.PortID,
		&i.WhisparrID,
		&i.StashID,
		&i.Charter,
		&i.Registry,
		&i.Path,
		&i.SizeBytes,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Resolution,
		&i.Oshash,
		&i.Coordinates,
		&i.Md5,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FleetID,
	)
	return i, err
}

const getVoyageByCoordinates = `-- name: GetVoyageByCoordinates :one
SELECT id, title, sort_title, overview, launch_date, distance, port_id, whisparr_id, stash_id, charter, registry, path, size_bytes, video_codec, audio_codec, resolution, oshash, coordinates, md5, cover_path, created_at, updated_at, fleet_id FROM qar.voyages WHERE coordinates = $1
`

func (q *Queries) GetVoyageByCoordinates(ctx context.Context, coordinates *string) (QarVoyage, error) {
	row := q.db.QueryRow(ctx, getVoyageByCoordinates, coordinates)
	var i QarVoyage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SortTitle,
		&i.Overview,
		&i.LaunchDate,
		&i.Distance,
		&i.PortID,
		&i.WhisparrID,
		&i.StashID,
		&i.Charter,
		&i.Registry,
		&i.Path,
		&i.SizeBytes,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Resolution,
		&i.Oshash,
		&i.Coordinates,
		&i.Md5,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FleetID,
	)
	return i, err
}

const getVoyageByID = `-- name: GetVoyageByID :one

SELECT id, title, sort_title, overview, launch_date, distance, port_id, whisparr_id, stash_id, charter, registry, path, size_bytes, video_codec, audio_codec, resolution, oshash, coordinates, md5, cover_path, created_at, updated_at, fleet_id FROM qar.voyages WHERE id = $1
`

// Voyages (Adult Scenes) - QAR obfuscated queries
func (q *Queries) GetVoyageByID(ctx context.Context, id uuid.UUID) (QarVoyage, error) {
	row := q.db.QueryRow(ctx, getVoyageByID, id)
	var i QarVoyage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SortTitle,
		&i.Overview,
		&i.LaunchDate,
		&i.Distance,
		&i.PortID,
		&i.WhisparrID,
		&i.StashID,
		&i.Charter,
		&i.Registry,
		&i.Path,
		&i.SizeBytes,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Resolution,
		&i.Oshash,
		&i.Coordinates,
		&i.Md5,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FleetID,
	)
	return i, err
}

const getVoyageByOshash = `-- name: GetVoyageByOshash :one
SELECT id, title, sort_title, overview, launch_date, distance, port_id, whisparr_id, stash_id, charter, registry, path, size_bytes, video_codec, audio_codec, resolution, oshash, coordinates, md5, cover_path, created_at, updated_at, fleet_id FROM qar.voyages WHERE oshash = $1
`

func (q *Queries) GetVoyageByOshash(ctx context.Context, oshash *string) (QarVoyage, error) {
	row := q.db.QueryRow(ctx, getVoyageByOshash, oshash)
	var i QarVoyage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SortTitle,
		&i.Overview,
		&i.LaunchDate,
		&i.Distance,
		&i.PortID,
		&i.WhisparrID,
		&i.StashID,
		&i.Charter,
		&i.Registry,
		&i.Path,
		&i.SizeBytes,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Resolution,
		&i.Oshash,
		&i.Coordinates,
		&i.Md5,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FleetID,
	)
	return i, err
}

const getVoyageByPath = `-- name: GetVoyageByPath :one
SELECT id, title, sort_title, overview, launch_date, distance, port_id, whisparr_id, stash_id, charter, registry, path, size_bytes, video_codec, audio_codec, resolution, oshash, coordinates, md5, cover_path, created_at, updated_at, fleet_id FROM qar.voyages WHERE path = $1
`

func (q *Queries) GetVoyageByPath(ctx context.Context, path string) (QarVoyage, error) {
	row := q.db.QueryRow(ctx, getVoyageByPath, path)
	var i QarVoyage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SortTitle,
		&i.Overview,
		&i.LaunchDate,
		&i.Distance,
		&i.PortID,
		&i.WhisparrID,
		&i.StashID,
		&i.Charter,
		&i.Registry,
		&i.Path,
		&i.SizeBytes,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Resolution,
		&i.Oshash,
		&i.Coordinates,
		&i.Md5,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FleetID,
	)
	return i, err
}

const listVoyages = `-- name: ListVoyages :many
SELECT id, title, sort_title, overview, launch_date, distance, port_id, whisparr_id, stash_id, charter, registry, path, size_bytes, video_codec, audio_codec, resolution, oshash, coordinates, md5, cover_path, created_at, updated_at, fleet_id FROM qar.voyages
ORDER BY title
LIMIT $1 OFFSET $2
`

type ListVoyagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVoyages(ctx context.Context, arg ListVoyagesParams) ([]QarVoyage, error) {
	rows, err := q.db.Query(ctx, listVoyages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QarVoyage{}
	for rows.Next() {
		var i QarVoyage
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SortTitle,
			&i.Overview,
			&i.LaunchDate,
			&i.Distance,
			&i.PortID,
			&i.WhisparrID,
			&i.StashID,
			&i.Charter,
			&i.Registry,
			&i.Path,
			&i.SizeBytes,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Resolution,
			&i.Oshash,
			&i.Coordinates,
			&i.Md5,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FleetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoyagesByFleet = `-- name: ListVoyagesByFleet :many
SELECT id, title, sort_title, overview, launch_date, distance, port_id, whisparr_id, stash_id, charter, registry, path, size_bytes, video_codec, audio_codec, resolution, oshash, coordinates, md5, cover_path, created_at, updated_at, fleet_id FROM qar.voyages
WHERE fleet_id = $1
ORDER BY title
LIMIT $2 OFFSET $3
`

type ListVoyagesByFleetParams struct {
	FleetID uuid.UUID `json:"fleetId"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListVoyagesByFleet(ctx context.Context, arg ListVoyagesByFleetParams) ([]QarVoyage, error) {
	rows, err := q.db.Query(ctx, listVoyagesByFleet, arg.FleetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QarVoyage{}
	for rows.Next() {
		var i QarVoyage
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SortTitle,
			&i.Overview,
			&i.LaunchDate,
			&i.Distance,
			&i.PortID,
			&i.WhisparrID,
			&i.StashID,
			&i.Charter,
			&i.Registry,
			&i.Path,
			&i.SizeBytes,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Resolution,
			&i.Oshash,
			&i.Coordinates,
			&i.Md5,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FleetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoyagesByPort = `-- name: ListVoyagesByPort :many
SELECT id, title, sort_title, overview, launch_date, distance, port_id, whisparr_id, stash_id, charter, registry, path, size_bytes, video_codec, audio_codec, resolution, oshash, coordinates, md5, cover_path, created_at, updated_at, fleet_id FROM qar.voyages
WHERE port_id = $1
ORDER BY launch_date DESC
LIMIT $2 OFFSET $3
`

type ListVoyagesByPortParams struct {
	PortID pgtype.UUID `json:"portId"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListVoyagesByPort(ctx context.Context, arg ListVoyagesByPortParams) ([]QarVoyage, error) {
	rows, err := q.db.Query(ctx, listVoyagesByPort, arg.PortID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QarVoyage{}
	for rows.Next() {
		var i QarVoyage
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SortTitle,
			&i.Overview,
			&i.LaunchDate,
			&i.Distance,
			&i.PortID,
			&i.WhisparrID,
			&i.StashID,
			&i.Charter,
			&i.Registry,
			&i.Path,
			&i.SizeBytes,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Resolution,
			&i.Oshash,
			&i.Coordinates,
			&i.Md5,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FleetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVoyages = `-- name: SearchVoyages :many
SELECT id, title, sort_title, overview, launch_date, distance, port_id, whisparr_id, stash_id, charter, registry, path, size_bytes, video_codec, audio_codec, resolution, oshash, coordinates, md5, cover_path, created_at, updated_at, fleet_id FROM qar.voyages
WHERE title ILIKE '%' || $1 || '%'
ORDER BY title
LIMIT $2 OFFSET $3
`

type SearchVoyagesParams struct {
	Column1 *string `json:"column1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) SearchVoyages(ctx context.Context, arg SearchVoyagesParams) ([]QarVoyage, error) {
	rows, err := q.db.Query(ctx, searchVoyages, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QarVoyage{}
	for rows.Next() {
		var i QarVoyage
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SortTitle,
			&i.Overview,
			&i.LaunchDate,
			&i.Distance,
			&i.PortID,
			&i.WhisparrID,
			&i.StashID,
			&i.Charter,
			&i.Registry,
			&i.Path,
			&i.SizeBytes,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Resolution,
			&i.Oshash,
			&i.Coordinates,
			&i.Md5,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FleetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoyage = `-- name: UpdateVoyage :one
UPDATE qar.voyages
SET
    fleet_id = $2,
    title = $3,
    sort_title = $4,
    overview = $5,
    launch_date = $6,
    distance = $7,
    port_id = $8,
    whisparr_id = $9,
    stash_id = $10,
    charter = $11,
    registry = $12,
    path = $13,
    size_bytes = $14,
    video_codec = $15,
    audio_codec = $16,
    resolution = $17,
    oshash = $18,
    coordinates = $19,
    md5 = $20,
    cover_path = $21
WHERE id = $1
RETURNING id, title, sort_title, overview, launch_date, distance, port_id, whisparr_id, stash_id, charter, registry, path, size_bytes, video_codec, audio_codec, resolution, oshash, coordinates, md5, cover_path, created_at, updated_at, fleet_id
`

type UpdateVoyageParams struct {
	ID          uuid.UUID   `json:"id"`
	FleetID     uuid.UUID   `json:"fleetId"`
	Title       string      `json:"title"`
	SortTitle   *string     `json:"sortTitle"`
	Overview    *string     `json:"overview"`
	LaunchDate  pgtype.Date `json:"launchDate"`
	Distance    *int32      `json:"distance"`
	PortID      pgtype.UUID `json:"portId"`
	WhisparrID  *int32      `json:"whisparrId"`
	StashID     *string     `json:"stashId"`
	Charter     *string     `json:"charter"`
	Registry    *string     `json:"registry"`
	Path        string      `json:"path"`
	SizeBytes   *int64      `json:"sizeBytes"`
	VideoCodec  *string     `json:"videoCodec"`
	AudioCodec  *string     `json:"audioCodec"`
	Resolution  *string     `json:"resolution"`
	Oshash      *string     `json:"oshash"`
	Coordinates *string     `json:"coordinates"`
	Md5         *string     `json:"md5"`
	CoverPath   *string     `json:"coverPath"`
}

func (q *Queries) UpdateVoyage(ctx context.Context, arg UpdateVoyageParams) (QarVoyage, error) {
	row := q.db.QueryRow(ctx, updateVoyage,
		arg.ID,
		arg.FleetID,
		arg.Title,
		arg.SortTitle,
		arg.Overview,
		arg.LaunchDate,
		arg.Distance,
		arg.PortID,
		arg.WhisparrID,
		arg.StashID,
		arg.Charter,
		arg.Registry,
		arg.Path,
		arg.SizeBytes,
		arg.VideoCodec,
		arg.AudioCodec,
		arg.Resolution,
		arg.Oshash,
		arg.Coordinates,
		arg.Md5,
		arg.CoverPath,
	)
	var i QarVoyage
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SortTitle,
		&i.Overview,
		&i.LaunchDate,
		&i.Distance,
		&i.PortID,
		&i.WhisparrID,
		&i.StashID,
		&i.Charter,
		&i.Registry,
		&i.Path,
		&i.SizeBytes,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Resolution,
		&i.Oshash,
		&i.Coordinates,
		&i.Md5,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FleetID,
	)
	return i, err
}
