// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddPolicy implements addPolicy operation.
	//
	// Add a new authorization policy (admin only).
	//
	// POST /api/v1/rbac/policies
	AddPolicy(ctx context.Context, req *PolicyRequest) (AddPolicyRes, error)
	// AdminCreateOIDCProvider implements adminCreateOIDCProvider operation.
	//
	// Creates a new OIDC provider configuration.
	//
	// POST /api/v1/admin/oidc/providers
	AdminCreateOIDCProvider(ctx context.Context, req *CreateOIDCProviderRequest) (AdminCreateOIDCProviderRes, error)
	// AdminDeleteOIDCProvider implements adminDeleteOIDCProvider operation.
	//
	// Deletes an OIDC provider configuration.
	//
	// DELETE /api/v1/admin/oidc/providers/{providerId}
	AdminDeleteOIDCProvider(ctx context.Context, params AdminDeleteOIDCProviderParams) (AdminDeleteOIDCProviderRes, error)
	// AdminDisableOIDCProvider implements adminDisableOIDCProvider operation.
	//
	// Disables an OIDC provider.
	//
	// POST /api/v1/admin/oidc/providers/{providerId}/disable
	AdminDisableOIDCProvider(ctx context.Context, params AdminDisableOIDCProviderParams) (AdminDisableOIDCProviderRes, error)
	// AdminEnableOIDCProvider implements adminEnableOIDCProvider operation.
	//
	// Enables an OIDC provider.
	//
	// POST /api/v1/admin/oidc/providers/{providerId}/enable
	AdminEnableOIDCProvider(ctx context.Context, params AdminEnableOIDCProviderParams) (AdminEnableOIDCProviderRes, error)
	// AdminGetOIDCProvider implements adminGetOIDCProvider operation.
	//
	// Returns detailed OIDC provider configuration.
	//
	// GET /api/v1/admin/oidc/providers/{providerId}
	AdminGetOIDCProvider(ctx context.Context, params AdminGetOIDCProviderParams) (AdminGetOIDCProviderRes, error)
	// AdminGetRadarrQualityProfiles implements adminGetRadarrQualityProfiles operation.
	//
	// Returns all quality profiles configured in Radarr.
	// Useful for mapping quality profiles during sync configuration.
	// Admin only.
	//
	// GET /api/v1/admin/integrations/radarr/quality-profiles
	AdminGetRadarrQualityProfiles(ctx context.Context) (AdminGetRadarrQualityProfilesRes, error)
	// AdminGetRadarrRootFolders implements adminGetRadarrRootFolders operation.
	//
	// Returns all root folders configured in Radarr.
	// These are the library paths that Radarr monitors for movies.
	// Admin only.
	//
	// GET /api/v1/admin/integrations/radarr/root-folders
	AdminGetRadarrRootFolders(ctx context.Context) (AdminGetRadarrRootFoldersRes, error)
	// AdminGetRadarrStatus implements adminGetRadarrStatus operation.
	//
	// Returns the current Radarr integration status including connection health,
	// sync status, and last sync information. Admin only.
	//
	// GET /api/v1/admin/integrations/radarr/status
	AdminGetRadarrStatus(ctx context.Context) (AdminGetRadarrStatusRes, error)
	// AdminListOIDCProviders implements adminListOIDCProviders operation.
	//
	// Returns all OIDC providers including disabled ones.
	//
	// GET /api/v1/admin/oidc/providers
	AdminListOIDCProviders(ctx context.Context) (AdminListOIDCProvidersRes, error)
	// AdminSetDefaultOIDCProvider implements adminSetDefaultOIDCProvider operation.
	//
	// Sets an OIDC provider as the default for SSO.
	//
	// POST /api/v1/admin/oidc/providers/{providerId}/default
	AdminSetDefaultOIDCProvider(ctx context.Context, params AdminSetDefaultOIDCProviderParams) (AdminSetDefaultOIDCProviderRes, error)
	// AdminTriggerRadarrSync implements adminTriggerRadarrSync operation.
	//
	// Triggers a full library sync from Radarr to Revenge.
	// This is an asynchronous operation - check status endpoint for progress.
	// Admin only.
	//
	// POST /api/v1/admin/integrations/radarr/sync
	AdminTriggerRadarrSync(ctx context.Context) (AdminTriggerRadarrSyncRes, error)
	// AdminUpdateOIDCProvider implements adminUpdateOIDCProvider operation.
	//
	// Updates an OIDC provider configuration.
	//
	// PATCH /api/v1/admin/oidc/providers/{providerId}
	AdminUpdateOIDCProvider(ctx context.Context, req *UpdateOIDCProviderRequest, params AdminUpdateOIDCProviderParams) (AdminUpdateOIDCProviderRes, error)
	// AssignRole implements assignRole operation.
	//
	// Assign a role to a user (admin only).
	//
	// POST /api/v1/rbac/users/{userId}/roles
	AssignRole(ctx context.Context, req *AssignRoleRequest, params AssignRoleParams) (AssignRoleRes, error)
	// AutocompleteMovies implements autocompleteMovies operation.
	//
	// Provides search suggestions for movie titles.
	// Useful for search-as-you-type interfaces.
	//
	// GET /api/v1/search/movies/autocomplete
	AutocompleteMovies(ctx context.Context, params AutocompleteMoviesParams) (AutocompleteMoviesRes, error)
	// ChangePassword implements changePassword operation.
	//
	// Change password for authenticated user (requires old password).
	//
	// POST /api/v1/auth/change-password
	ChangePassword(ctx context.Context, req *ChangePasswordRequest) (ChangePasswordRes, error)
	// CreateAPIKey implements createAPIKey operation.
	//
	// Generate a new API key for the authenticated user.
	//
	// POST /api/v1/apikeys
	CreateAPIKey(ctx context.Context, req *CreateAPIKeyRequest) (CreateAPIKeyRes, error)
	// CreateLibrary implements createLibrary operation.
	//
	// Create a new media library. Admin only.
	//
	// POST /api/v1/libraries
	CreateLibrary(ctx context.Context, req *CreateLibraryRequest) (CreateLibraryRes, error)
	// DeleteLibrary implements deleteLibrary operation.
	//
	// Delete a library and all its content. Admin only.
	//
	// DELETE /api/v1/libraries/{libraryId}
	DeleteLibrary(ctx context.Context, params DeleteLibraryParams) (DeleteLibraryRes, error)
	// DeleteUserSetting implements deleteUserSetting operation.
	//
	// Delete a user setting (revert to default).
	//
	// DELETE /api/v1/settings/user/{key}
	DeleteUserSetting(ctx context.Context, params DeleteUserSettingParams) (DeleteUserSettingRes, error)
	// DeleteWatchProgress implements deleteWatchProgress operation.
	//
	// Remove watch progress for a movie.
	//
	// DELETE /api/v1/movies/{id}/progress
	DeleteWatchProgress(ctx context.Context, params DeleteWatchProgressParams) (DeleteWatchProgressRes, error)
	// DisableMFA implements disableMFA operation.
	//
	// Turn off MFA requirement for login.
	//
	// POST /api/v1/mfa/disable
	DisableMFA(ctx context.Context) (DisableMFARes, error)
	// DisableTOTP implements disableTOTP operation.
	//
	// Remove TOTP from user's MFA methods.
	//
	// DELETE /api/v1/mfa/totp
	DisableTOTP(ctx context.Context) (DisableTOTPRes, error)
	// EnableMFA implements enableMFA operation.
	//
	// Require MFA for login (at least one method must be configured).
	//
	// POST /api/v1/mfa/enable
	EnableMFA(ctx context.Context) (EnableMFARes, error)
	// ForgotPassword implements forgotPassword operation.
	//
	// Send password reset token to user's email address.
	//
	// POST /api/v1/auth/forgot-password
	ForgotPassword(ctx context.Context, req *ForgotPasswordRequest) (ForgotPasswordRes, error)
	// GenerateBackupCodes implements generateBackupCodes operation.
	//
	// Generate new set of 10 one-time use backup codes.
	//
	// POST /api/v1/mfa/backup-codes/generate
	GenerateBackupCodes(ctx context.Context) (GenerateBackupCodesRes, error)
	// GetAPIKey implements getAPIKey operation.
	//
	// Get details of a specific API key.
	//
	// GET /api/v1/apikeys/{keyId}
	GetAPIKey(ctx context.Context, params GetAPIKeyParams) (GetAPIKeyRes, error)
	// GetActivityStats implements getActivityStats operation.
	//
	// Get activity log statistics.
	//
	// GET /api/v1/admin/activity/stats
	GetActivityStats(ctx context.Context) (GetActivityStatsRes, error)
	// GetCollection implements getCollection operation.
	//
	// Get detailed information about a collection.
	//
	// GET /api/v1/collections/{id}
	GetCollection(ctx context.Context, params GetCollectionParams) (GetCollectionRes, error)
	// GetCollectionMetadata implements getCollectionMetadata operation.
	//
	// Fetch detailed collection information from TMDb by collection ID.
	// Returns collection metadata including all movies in the collection.
	//
	// GET /api/v1/metadata/collection/{tmdbId}
	GetCollectionMetadata(ctx context.Context, params GetCollectionMetadataParams) (GetCollectionMetadataRes, error)
	// GetCollectionMovies implements getCollectionMovies operation.
	//
	// Get all movies in a collection.
	//
	// GET /api/v1/collections/{id}/movies
	GetCollectionMovies(ctx context.Context, params GetCollectionMoviesParams) (GetCollectionMoviesRes, error)
	// GetContinueWatching implements getContinueWatching operation.
	//
	// Get movies the user is currently watching.
	//
	// GET /api/v1/movies/continue-watching
	GetContinueWatching(ctx context.Context, params GetContinueWatchingParams) (GetContinueWatchingRes, error)
	// GetCurrentSession implements getCurrentSession operation.
	//
	// Get information about the current session.
	//
	// GET /api/v1/sessions/current
	GetCurrentSession(ctx context.Context) (GetCurrentSessionRes, error)
	// GetCurrentUser implements getCurrentUser operation.
	//
	// Get the currently authenticated user's profile.
	//
	// GET /api/v1/users/me
	GetCurrentUser(ctx context.Context) (GetCurrentUserRes, error)
	// GetLibrary implements getLibrary operation.
	//
	// Get detailed information about a library.
	//
	// GET /api/v1/libraries/{libraryId}
	GetLibrary(ctx context.Context, params GetLibraryParams) (GetLibraryRes, error)
	// GetLiveness implements getLiveness operation.
	//
	// Checks if the service is alive and running.
	// This should always return 200 unless the process is deadlocked.
	// Used by Kubernetes liveness probes.
	//
	// GET /healthz
	GetLiveness(ctx context.Context) (*HealthCheck, error)
	// GetMFAStatus implements getMFAStatus operation.
	//
	// Get current MFA configuration status for authenticated user.
	//
	// GET /api/v1/mfa/status
	GetMFAStatus(ctx context.Context) (GetMFAStatusRes, error)
	// GetMovie implements getMovie operation.
	//
	// Get detailed information about a movie.
	//
	// GET /api/v1/movies/{id}
	GetMovie(ctx context.Context, params GetMovieParams) (GetMovieRes, error)
	// GetMovieCast implements getMovieCast operation.
	//
	// Get cast members for a movie.
	//
	// GET /api/v1/movies/{id}/cast
	GetMovieCast(ctx context.Context, params GetMovieCastParams) (GetMovieCastRes, error)
	// GetMovieCollection implements getMovieCollection operation.
	//
	// Get the collection this movie belongs to.
	//
	// GET /api/v1/movies/{id}/collection
	GetMovieCollection(ctx context.Context, params GetMovieCollectionParams) (GetMovieCollectionRes, error)
	// GetMovieCrew implements getMovieCrew operation.
	//
	// Get crew members for a movie.
	//
	// GET /api/v1/movies/{id}/crew
	GetMovieCrew(ctx context.Context, params GetMovieCrewParams) (GetMovieCrewRes, error)
	// GetMovieFiles implements getMovieFiles operation.
	//
	// Get physical files for a movie.
	//
	// GET /api/v1/movies/{id}/files
	GetMovieFiles(ctx context.Context, params GetMovieFilesParams) (GetMovieFilesRes, error)
	// GetMovieGenres implements getMovieGenres operation.
	//
	// Get genres for a movie.
	//
	// GET /api/v1/movies/{id}/genres
	GetMovieGenres(ctx context.Context, params GetMovieGenresParams) (GetMovieGenresRes, error)
	// GetMovieMetadata implements getMovieMetadata operation.
	//
	// Fetch detailed movie information from TMDb by TMDb ID.
	// Returns full metadata including cast, crew, and images.
	//
	// GET /api/v1/metadata/movie/{tmdbId}
	GetMovieMetadata(ctx context.Context, params GetMovieMetadataParams) (GetMovieMetadataRes, error)
	// GetProxiedImage implements getProxiedImage operation.
	//
	// Proxy images from TMDb image server. This caches images locally
	// and serves them to clients without exposing TMDb API keys.
	//
	// GET /api/v1/images/{type}/{size}/{path}
	GetProxiedImage(ctx context.Context, params GetProxiedImageParams) (GetProxiedImageRes, error)
	// GetReadiness implements getReadiness operation.
	//
	// Checks if the service is ready to accept traffic.
	// Returns 200 only if all dependencies (database, cache, etc.) are available.
	// Used by Kubernetes readiness probes.
	//
	// GET /readyz
	GetReadiness(ctx context.Context) (GetReadinessRes, error)
	// GetRecentActions implements getRecentActions operation.
	//
	// Get recent distinct action types for filtering.
	//
	// GET /api/v1/admin/activity/actions
	GetRecentActions(ctx context.Context, params GetRecentActionsParams) (GetRecentActionsRes, error)
	// GetRecentlyAdded implements getRecentlyAdded operation.
	//
	// Get movies ordered by when they were added to the library.
	//
	// GET /api/v1/movies/recently-added
	GetRecentlyAdded(ctx context.Context, params GetRecentlyAddedParams) (GetRecentlyAddedRes, error)
	// GetResourceActivityLogs implements getResourceActivityLogs operation.
	//
	// Get activity logs for a specific resource.
	//
	// GET /api/v1/admin/activity/resources/{resourceType}/{resourceId}
	GetResourceActivityLogs(ctx context.Context, params GetResourceActivityLogsParams) (GetResourceActivityLogsRes, error)
	// GetSearchFacets implements getSearchFacets operation.
	//
	// Returns available facet values for filtering (genres, years, etc.).
	// Use this to populate filter dropdowns in the UI.
	//
	// GET /api/v1/search/movies/facets
	GetSearchFacets(ctx context.Context) (GetSearchFacetsRes, error)
	// GetServerSetting implements getServerSetting operation.
	//
	// Retrieve a specific server setting by key.
	//
	// GET /api/v1/settings/server/{key}
	GetServerSetting(ctx context.Context, params GetServerSettingParams) (GetServerSettingRes, error)
	// GetSimilarMovies implements getSimilarMovies operation.
	//
	// Get movies similar to this one based on TMDb recommendations.
	//
	// GET /api/v1/movies/{id}/similar
	GetSimilarMovies(ctx context.Context, params GetSimilarMoviesParams) (GetSimilarMoviesRes, error)
	// GetStartup implements getStartup operation.
	//
	// Checks if the service has completed initialization.
	// Returns 200 only after startup is complete.
	// Used by Kubernetes startup probes.
	//
	// GET /startupz
	GetStartup(ctx context.Context) (GetStartupRes, error)
	// GetTopRated implements getTopRated operation.
	//
	// Get highest-rated movies.
	//
	// GET /api/v1/movies/top-rated
	GetTopRated(ctx context.Context, params GetTopRatedParams) (GetTopRatedRes, error)
	// GetUserActivityLogs implements getUserActivityLogs operation.
	//
	// Get activity logs for a specific user.
	//
	// GET /api/v1/admin/activity/users/{userId}
	GetUserActivityLogs(ctx context.Context, params GetUserActivityLogsParams) (GetUserActivityLogsRes, error)
	// GetUserById implements getUserById operation.
	//
	// Get a user's public profile information.
	//
	// GET /api/v1/users/{userId}
	GetUserById(ctx context.Context, params GetUserByIdParams) (GetUserByIdRes, error)
	// GetUserMovieStats implements getUserMovieStats operation.
	//
	// Get statistics about user's movie watching.
	//
	// GET /api/v1/movies/stats
	GetUserMovieStats(ctx context.Context) (GetUserMovieStatsRes, error)
	// GetUserPreferences implements getUserPreferences operation.
	//
	// Get notification and display preferences for the authenticated user.
	//
	// GET /api/v1/users/me/preferences
	GetUserPreferences(ctx context.Context) (GetUserPreferencesRes, error)
	// GetUserRoles implements getUserRoles operation.
	//
	// Get all roles assigned to a user.
	//
	// GET /api/v1/rbac/users/{userId}/roles
	GetUserRoles(ctx context.Context, params GetUserRolesParams) (GetUserRolesRes, error)
	// GetUserSetting implements getUserSetting operation.
	//
	// Retrieve a specific user setting by key.
	//
	// GET /api/v1/settings/user/{key}
	GetUserSetting(ctx context.Context, params GetUserSettingParams) (GetUserSettingRes, error)
	// GetWatchHistory implements getWatchHistory operation.
	//
	// Get user's watched movies.
	//
	// GET /api/v1/movies/watch-history
	GetWatchHistory(ctx context.Context, params GetWatchHistoryParams) (GetWatchHistoryRes, error)
	// GetWatchProgress implements getWatchProgress operation.
	//
	// Get user's watch progress for a movie.
	//
	// GET /api/v1/movies/{id}/progress
	GetWatchProgress(ctx context.Context, params GetWatchProgressParams) (GetWatchProgressRes, error)
	// GrantLibraryPermission implements grantLibraryPermission operation.
	//
	// Grant a user permission to access a library. Admin only.
	//
	// POST /api/v1/libraries/{libraryId}/permissions
	GrantLibraryPermission(ctx context.Context, req *GrantLibraryPermissionReq, params GrantLibraryPermissionParams) (GrantLibraryPermissionRes, error)
	// HandleRadarrWebhook implements handleRadarrWebhook operation.
	//
	// Endpoint for receiving webhook notifications from Radarr.
	// Supports events: Grab, Download, Rename, MovieDelete, MovieFileDelete, Health.
	// Configure this URL in Radarr Settings > Connect > Webhook.
	//
	// POST /api/v1/webhooks/radarr
	HandleRadarrWebhook(ctx context.Context, req *RadarrWebhookPayload) (HandleRadarrWebhookRes, error)
	// InitOIDCLink implements initOIDCLink operation.
	//
	// Initiates the flow to link an OIDC provider to the user's account.
	//
	// POST /api/v1/users/me/oidc/{provider}/link
	InitOIDCLink(ctx context.Context, params InitOIDCLinkParams) (InitOIDCLinkRes, error)
	// ListAPIKeys implements listAPIKeys operation.
	//
	// Get all API keys for the authenticated user.
	//
	// GET /api/v1/apikeys
	ListAPIKeys(ctx context.Context) (ListAPIKeysRes, error)
	// ListLibraries implements listLibraries operation.
	//
	// List all libraries the authenticated user can access. Admins see all libraries.
	//
	// GET /api/v1/libraries
	ListLibraries(ctx context.Context) (ListLibrariesRes, error)
	// ListLibraryPermissions implements listLibraryPermissions operation.
	//
	// List all user permissions for a library. Admin only.
	//
	// GET /api/v1/libraries/{libraryId}/permissions
	ListLibraryPermissions(ctx context.Context, params ListLibraryPermissionsParams) (ListLibraryPermissionsRes, error)
	// ListLibraryScans implements listLibraryScans operation.
	//
	// List scan history for a library.
	//
	// GET /api/v1/libraries/{libraryId}/scans
	ListLibraryScans(ctx context.Context, params ListLibraryScansParams) (ListLibraryScansRes, error)
	// ListMovies implements listMovies operation.
	//
	// Get a paginated list of movies with optional filtering and sorting.
	//
	// GET /api/v1/movies
	ListMovies(ctx context.Context, params ListMoviesParams) (ListMoviesRes, error)
	// ListOIDCProviders implements listOIDCProviders operation.
	//
	// Returns a list of enabled OIDC providers for login.
	//
	// GET /api/v1/oidc/providers
	ListOIDCProviders(ctx context.Context) (*OIDCProviderListResponse, error)
	// ListPolicies implements listPolicies operation.
	//
	// Get all authorization policies (admin only).
	//
	// GET /api/v1/rbac/policies
	ListPolicies(ctx context.Context) (ListPoliciesRes, error)
	// ListServerSettings implements listServerSettings operation.
	//
	// Retrieve all server-wide configuration settings.
	//
	// GET /api/v1/settings/server
	ListServerSettings(ctx context.Context) (ListServerSettingsRes, error)
	// ListSessions implements listSessions operation.
	//
	// Get all active sessions for the authenticated user.
	//
	// GET /api/v1/sessions
	ListSessions(ctx context.Context) (ListSessionsRes, error)
	// ListUserOIDCLinks implements listUserOIDCLinks operation.
	//
	// Returns all OIDC providers linked to the current user.
	//
	// GET /api/v1/users/me/oidc
	ListUserOIDCLinks(ctx context.Context) (ListUserOIDCLinksRes, error)
	// ListUserSettings implements listUserSettings operation.
	//
	// Retrieve all settings for the authenticated user.
	//
	// GET /api/v1/settings/user
	ListUserSettings(ctx context.Context) (ListUserSettingsRes, error)
	// Login implements login operation.
	//
	// Authenticate user and return access token and refresh token.
	//
	// POST /api/v1/auth/login
	Login(ctx context.Context, req *LoginRequest) (LoginRes, error)
	// Logout implements logout operation.
	//
	// Invalidate the current refresh token.
	//
	// POST /api/v1/auth/logout
	Logout(ctx context.Context, req *LogoutRequest) (LogoutRes, error)
	// LogoutAll implements logoutAll operation.
	//
	// Revoke all sessions for the authenticated user (logout everywhere).
	//
	// DELETE /api/v1/sessions
	LogoutAll(ctx context.Context) (LogoutAllRes, error)
	// LogoutCurrent implements logoutCurrent operation.
	//
	// Revoke the current session (logout).
	//
	// DELETE /api/v1/sessions/current
	LogoutCurrent(ctx context.Context) (LogoutCurrentRes, error)
	// MarkAsWatched implements markAsWatched operation.
	//
	// Mark a movie as fully watched.
	//
	// POST /api/v1/movies/{id}/watched
	MarkAsWatched(ctx context.Context, params MarkAsWatchedParams) (MarkAsWatchedRes, error)
	// OidcAuthorize implements oidcAuthorize operation.
	//
	// Redirects to the OIDC provider's authorization endpoint.
	//
	// GET /api/v1/oidc/auth/{provider}
	OidcAuthorize(ctx context.Context, params OidcAuthorizeParams) (OidcAuthorizeRes, error)
	// OidcCallback implements oidcCallback operation.
	//
	// Handles the OAuth2 callback from OIDC provider.
	//
	// GET /api/v1/oidc/callback/{provider}
	OidcCallback(ctx context.Context, params OidcCallbackParams) (OidcCallbackRes, error)
	// RefreshMovieMetadata implements refreshMovieMetadata operation.
	//
	// Trigger a metadata refresh from TMDb/Radarr.
	//
	// POST /api/v1/movies/{id}/refresh
	RefreshMovieMetadata(ctx context.Context, params RefreshMovieMetadataParams) (RefreshMovieMetadataRes, error)
	// RefreshSession implements refreshSession operation.
	//
	// Refresh access token using refresh token.
	//
	// POST /api/v1/sessions/refresh
	RefreshSession(ctx context.Context, req *RefreshSessionRequest) (RefreshSessionRes, error)
	// RefreshToken implements refreshToken operation.
	//
	// Exchange refresh token for a new access token.
	//
	// POST /api/v1/auth/refresh
	RefreshToken(ctx context.Context, req *RefreshRequest) (RefreshTokenRes, error)
	// RegenerateBackupCodes implements regenerateBackupCodes operation.
	//
	// Delete all existing backup codes and generate a new set.
	//
	// POST /api/v1/mfa/backup-codes/regenerate
	RegenerateBackupCodes(ctx context.Context) (RegenerateBackupCodesRes, error)
	// Register implements register operation.
	//
	// Create a new user account with username, email, and password.
	//
	// POST /api/v1/auth/register
	Register(ctx context.Context, req *RegisterRequest) (RegisterRes, error)
	// ReindexSearch implements reindexSearch operation.
	//
	// Triggers a full reindex of all movies in the search engine.
	// This is an admin-only operation and may take a while for large libraries.
	//
	// POST /api/v1/search/reindex
	ReindexSearch(ctx context.Context) (ReindexSearchRes, error)
	// RemovePolicy implements removePolicy operation.
	//
	// Remove an authorization policy (admin only).
	//
	// DELETE /api/v1/rbac/policies
	RemovePolicy(ctx context.Context, req *PolicyRequest) (RemovePolicyRes, error)
	// RemoveRole implements removeRole operation.
	//
	// Remove a role from a user (admin only).
	//
	// DELETE /api/v1/rbac/users/{userId}/roles/{role}
	RemoveRole(ctx context.Context, params RemoveRoleParams) (RemoveRoleRes, error)
	// ResendVerification implements resendVerification operation.
	//
	// Resend email verification token to user's email address.
	//
	// POST /api/v1/auth/resend-verification
	ResendVerification(ctx context.Context) (ResendVerificationRes, error)
	// ResetPassword implements resetPassword operation.
	//
	// Reset password using token from password reset email.
	//
	// POST /api/v1/auth/reset-password
	ResetPassword(ctx context.Context, req *ResetPasswordRequest) (ResetPasswordRes, error)
	// RevokeAPIKey implements revokeAPIKey operation.
	//
	// Revoke (deactivate) an API key.
	//
	// DELETE /api/v1/apikeys/{keyId}
	RevokeAPIKey(ctx context.Context, params RevokeAPIKeyParams) (RevokeAPIKeyRes, error)
	// RevokeLibraryPermission implements revokeLibraryPermission operation.
	//
	// Revoke a user's permission for a library. Admin only.
	//
	// DELETE /api/v1/libraries/{libraryId}/permissions/{userId}
	RevokeLibraryPermission(ctx context.Context, params RevokeLibraryPermissionParams) (RevokeLibraryPermissionRes, error)
	// RevokeSession implements revokeSession operation.
	//
	// Revoke a specific session by ID.
	//
	// DELETE /api/v1/sessions/{sessionId}
	RevokeSession(ctx context.Context, params RevokeSessionParams) (RevokeSessionRes, error)
	// SearchActivityLogs implements searchActivityLogs operation.
	//
	// Search and filter activity logs with pagination.
	//
	// GET /api/v1/admin/activity
	SearchActivityLogs(ctx context.Context, params SearchActivityLogsParams) (SearchActivityLogsRes, error)
	// SearchLibraryMovies implements searchLibraryMovies operation.
	//
	// Full-text search across the movie library using Typesense.
	// Supports filtering by genres, year, status, and more.
	// Returns faceted results for filtering.
	//
	// GET /api/v1/search/movies
	SearchLibraryMovies(ctx context.Context, params SearchLibraryMoviesParams) (SearchLibraryMoviesRes, error)
	// SearchMovies implements searchMovies operation.
	//
	// Search movies by title using fuzzy matching.
	//
	// GET /api/v1/movies/search
	SearchMovies(ctx context.Context, params SearchMoviesParams) (SearchMoviesRes, error)
	// SearchMoviesMetadata implements searchMoviesMetadata operation.
	//
	// Search for movies in the TMDb database. This searches the external
	// metadata provider, not the local library. Use this to find movies
	// to add to your library or to identify unmatched files.
	//
	// GET /api/v1/metadata/search/movie
	SearchMoviesMetadata(ctx context.Context, params SearchMoviesMetadataParams) (SearchMoviesMetadataRes, error)
	// SetupTOTP implements setupTOTP operation.
	//
	// Generate TOTP secret and QR code for enrollment.
	//
	// POST /api/v1/mfa/totp/setup
	SetupTOTP(ctx context.Context, req *SetupTOTPReq) (SetupTOTPRes, error)
	// TriggerLibraryScan implements triggerLibraryScan operation.
	//
	// Start a library scan job. Admin only.
	//
	// POST /api/v1/libraries/{libraryId}/scan
	TriggerLibraryScan(ctx context.Context, req *TriggerLibraryScanReq, params TriggerLibraryScanParams) (TriggerLibraryScanRes, error)
	// UnlinkOIDCProvider implements unlinkOIDCProvider operation.
	//
	// Removes the link between user and OIDC provider.
	//
	// DELETE /api/v1/users/me/oidc/{provider}
	UnlinkOIDCProvider(ctx context.Context, params UnlinkOIDCProviderParams) (UnlinkOIDCProviderRes, error)
	// UpdateCurrentUser implements updateCurrentUser operation.
	//
	// Update the authenticated user's profile.
	//
	// PUT /api/v1/users/me
	UpdateCurrentUser(ctx context.Context, req *UserUpdate) (UpdateCurrentUserRes, error)
	// UpdateLibrary implements updateLibrary operation.
	//
	// Update library settings. Admin only.
	//
	// PUT /api/v1/libraries/{libraryId}
	UpdateLibrary(ctx context.Context, req *UpdateLibraryRequest, params UpdateLibraryParams) (UpdateLibraryRes, error)
	// UpdateServerSetting implements updateServerSetting operation.
	//
	// Update the value of a server setting.
	//
	// PUT /api/v1/settings/server/{key}
	UpdateServerSetting(ctx context.Context, req *SettingValue, params UpdateServerSettingParams) (UpdateServerSettingRes, error)
	// UpdateUserPreferences implements updateUserPreferences operation.
	//
	// Update notification and display preferences.
	//
	// PUT /api/v1/users/me/preferences
	UpdateUserPreferences(ctx context.Context, req *UserPreferencesUpdate) (UpdateUserPreferencesRes, error)
	// UpdateUserSetting implements updateUserSetting operation.
	//
	// Update the value of a user setting.
	//
	// PUT /api/v1/settings/user/{key}
	UpdateUserSetting(ctx context.Context, req *SettingValue, params UpdateUserSettingParams) (UpdateUserSettingRes, error)
	// UpdateWatchProgress implements updateWatchProgress operation.
	//
	// Update or create watch progress for a movie.
	//
	// POST /api/v1/movies/{id}/progress
	UpdateWatchProgress(ctx context.Context, req *UpdateWatchProgressReq, params UpdateWatchProgressParams) (UpdateWatchProgressRes, error)
	// UploadAvatar implements uploadAvatar operation.
	//
	// Upload a new avatar image.
	//
	// POST /api/v1/users/me/avatar
	UploadAvatar(ctx context.Context, req *UploadAvatarReq) (UploadAvatarRes, error)
	// VerifyEmail implements verifyEmail operation.
	//
	// Verify user email address with token from verification email.
	//
	// POST /api/v1/auth/verify-email
	VerifyEmail(ctx context.Context, req *VerifyEmailRequest) (VerifyEmailRes, error)
	// VerifyTOTP implements verifyTOTP operation.
	//
	// Verify TOTP code to complete enrollment and enable TOTP.
	//
	// POST /api/v1/mfa/totp/verify
	VerifyTOTP(ctx context.Context, req *VerifyTOTPReq) (VerifyTOTPRes, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
