// Code generated by ogen, DO NOT EDIT.
package ogen

type AddPolicyRes interface {
	addPolicyRes()
}

type AdminCreateOIDCProviderRes interface {
	adminCreateOIDCProviderRes()
}

type AdminDeleteOIDCProviderRes interface {
	adminDeleteOIDCProviderRes()
}

type AdminDisableOIDCProviderRes interface {
	adminDisableOIDCProviderRes()
}

type AdminEnableOIDCProviderRes interface {
	adminEnableOIDCProviderRes()
}

type AdminGetOIDCProviderRes interface {
	adminGetOIDCProviderRes()
}

type AdminListOIDCProvidersRes interface {
	adminListOIDCProvidersRes()
}

type AdminSetDefaultOIDCProviderRes interface {
	adminSetDefaultOIDCProviderRes()
}

type AdminUpdateOIDCProviderRes interface {
	adminUpdateOIDCProviderRes()
}

type AssignRoleRes interface {
	assignRoleRes()
}

type ChangePasswordRes interface {
	changePasswordRes()
}

type CreateAPIKeyRes interface {
	createAPIKeyRes()
}

type DeleteUserSettingRes interface {
	deleteUserSettingRes()
}

type ForgotPasswordRes interface {
	forgotPasswordRes()
}

type GetAPIKeyRes interface {
	getAPIKeyRes()
}

type GetActivityStatsRes interface {
	getActivityStatsRes()
}

type GetCurrentSessionRes interface {
	getCurrentSessionRes()
}

type GetCurrentUserRes interface {
	getCurrentUserRes()
}

type GetReadinessRes interface {
	getReadinessRes()
}

type GetRecentActionsRes interface {
	getRecentActionsRes()
}

type GetResourceActivityLogsRes interface {
	getResourceActivityLogsRes()
}

type GetServerSettingRes interface {
	getServerSettingRes()
}

type GetStartupRes interface {
	getStartupRes()
}

type GetUserActivityLogsRes interface {
	getUserActivityLogsRes()
}

type GetUserByIdRes interface {
	getUserByIdRes()
}

type GetUserPreferencesRes interface {
	getUserPreferencesRes()
}

type GetUserRolesRes interface {
	getUserRolesRes()
}

type GetUserSettingRes interface {
	getUserSettingRes()
}

type InitOIDCLinkRes interface {
	initOIDCLinkRes()
}

type ListAPIKeysRes interface {
	listAPIKeysRes()
}

type ListPoliciesRes interface {
	listPoliciesRes()
}

type ListServerSettingsRes interface {
	listServerSettingsRes()
}

type ListSessionsRes interface {
	listSessionsRes()
}

type ListUserOIDCLinksRes interface {
	listUserOIDCLinksRes()
}

type ListUserSettingsRes interface {
	listUserSettingsRes()
}

type LoginRes interface {
	loginRes()
}

type LogoutAllRes interface {
	logoutAllRes()
}

type LogoutCurrentRes interface {
	logoutCurrentRes()
}

type LogoutRes interface {
	logoutRes()
}

type OidcAuthorizeRes interface {
	oidcAuthorizeRes()
}

type OidcCallbackRes interface {
	oidcCallbackRes()
}

type RefreshSessionRes interface {
	refreshSessionRes()
}

type RefreshTokenRes interface {
	refreshTokenRes()
}

type RegisterRes interface {
	registerRes()
}

type RemovePolicyRes interface {
	removePolicyRes()
}

type RemoveRoleRes interface {
	removeRoleRes()
}

type ResendVerificationRes interface {
	resendVerificationRes()
}

type ResetPasswordRes interface {
	resetPasswordRes()
}

type RevokeAPIKeyRes interface {
	revokeAPIKeyRes()
}

type RevokeSessionRes interface {
	revokeSessionRes()
}

type SearchActivityLogsRes interface {
	searchActivityLogsRes()
}

type UnlinkOIDCProviderRes interface {
	unlinkOIDCProviderRes()
}

type UpdateCurrentUserRes interface {
	updateCurrentUserRes()
}

type UpdateServerSettingRes interface {
	updateServerSettingRes()
}

type UpdateUserPreferencesRes interface {
	updateUserPreferencesRes()
}

type UpdateUserSettingRes interface {
	updateUserSettingRes()
}

type UploadAvatarRes interface {
	uploadAvatarRes()
}

type VerifyEmailRes interface {
	verifyEmailRes()
}
