// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles bearerAuth security.
	// JWT access token from /api/v1/auth/login.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesBearerAuth = map[string][]string{
	AddPolicyOperation:             []string{},
	AssignRoleOperation:            []string{},
	ChangePasswordOperation:        []string{},
	DeleteUserSettingOperation:     []string{},
	GetCurrentSessionOperation:     []string{},
	GetCurrentUserOperation:        []string{},
	GetServerSettingOperation:      []string{},
	GetUserByIdOperation:           []string{},
	GetUserPreferencesOperation:    []string{},
	GetUserRolesOperation:          []string{},
	GetUserSettingOperation:        []string{},
	ListPoliciesOperation:          []string{},
	ListServerSettingsOperation:    []string{},
	ListSessionsOperation:          []string{},
	ListUserSettingsOperation:      []string{},
	LogoutOperation:                []string{},
	LogoutAllOperation:             []string{},
	LogoutCurrentOperation:         []string{},
	RemovePolicyOperation:          []string{},
	RemoveRoleOperation:            []string{},
	ResendVerificationOperation:    []string{},
	RevokeSessionOperation:         []string{},
	UpdateCurrentUserOperation:     []string{},
	UpdateServerSettingOperation:   []string{},
	UpdateUserPreferencesOperation: []string{},
	UpdateUserSettingOperation:     []string{},
	UploadAvatarOperation:          []string{},
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	// JWT access token from /api/v1/auth/login.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
