// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	ChangePasswordOperation        OperationName = "ChangePassword"
	DeleteUserSettingOperation     OperationName = "DeleteUserSetting"
	ForgotPasswordOperation        OperationName = "ForgotPassword"
	GetCurrentUserOperation        OperationName = "GetCurrentUser"
	GetLivenessOperation           OperationName = "GetLiveness"
	GetReadinessOperation          OperationName = "GetReadiness"
	GetServerSettingOperation      OperationName = "GetServerSetting"
	GetStartupOperation            OperationName = "GetStartup"
	GetUserByIdOperation           OperationName = "GetUserById"
	GetUserPreferencesOperation    OperationName = "GetUserPreferences"
	GetUserSettingOperation        OperationName = "GetUserSetting"
	ListServerSettingsOperation    OperationName = "ListServerSettings"
	ListUserSettingsOperation      OperationName = "ListUserSettings"
	LoginOperation                 OperationName = "Login"
	LogoutOperation                OperationName = "Logout"
	RefreshTokenOperation          OperationName = "RefreshToken"
	RegisterOperation              OperationName = "Register"
	ResendVerificationOperation    OperationName = "ResendVerification"
	ResetPasswordOperation         OperationName = "ResetPassword"
	UpdateCurrentUserOperation     OperationName = "UpdateCurrentUser"
	UpdateServerSettingOperation   OperationName = "UpdateServerSetting"
	UpdateUserPreferencesOperation OperationName = "UpdateUserPreferences"
	UpdateUserSettingOperation     OperationName = "UpdateUserSetting"
	UploadAvatarOperation          OperationName = "UploadAvatar"
	VerifyEmailOperation           OperationName = "VerifyEmail"
)
