// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package adultdb

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivitySeverity string

const (
	ActivitySeverityInfo     ActivitySeverity = "info"
	ActivitySeverityWarning  ActivitySeverity = "warning"
	ActivitySeverityError    ActivitySeverity = "error"
	ActivitySeverityCritical ActivitySeverity = "critical"
)

func (e *ActivitySeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivitySeverity(s)
	case string:
		*e = ActivitySeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivitySeverity: %T", src)
	}
	return nil
}

type NullActivitySeverity struct {
	ActivitySeverity ActivitySeverity `json:"activitySeverity"`
	Valid            bool             `json:"valid"` // Valid is true if ActivitySeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivitySeverity) Scan(value interface{}) error {
	if value == nil {
		ns.ActivitySeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivitySeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivitySeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivitySeverity), nil
}

type ActivityType string

const (
	ActivityTypeUserLogin       ActivityType = "user_login"
	ActivityTypeUserLogout      ActivityType = "user_logout"
	ActivityTypeUserCreated     ActivityType = "user_created"
	ActivityTypeUserUpdated     ActivityType = "user_updated"
	ActivityTypeUserDeleted     ActivityType = "user_deleted"
	ActivityTypePasswordChanged ActivityType = "password_changed"
	ActivityTypeSessionCreated  ActivityType = "session_created"
	ActivityTypeSessionExpired  ActivityType = "session_expired"
	ActivityTypeLibraryCreated  ActivityType = "library_created"
	ActivityTypeLibraryUpdated  ActivityType = "library_updated"
	ActivityTypeLibraryDeleted  ActivityType = "library_deleted"
	ActivityTypeLibraryScanned  ActivityType = "library_scanned"
	ActivityTypeContentPlayed   ActivityType = "content_played"
	ActivityTypeContentRated    ActivityType = "content_rated"
	ActivityTypeSettingsChanged ActivityType = "settings_changed"
	ActivityTypeApiError        ActivityType = "api_error"
	ActivityTypeSecurityEvent   ActivityType = "security_event"
)

func (e *ActivityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityType(s)
	case string:
		*e = ActivityType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityType: %T", src)
	}
	return nil
}

type NullActivityType struct {
	ActivityType ActivityType `json:"activityType"`
	Valid        bool         `json:"valid"` // Valid is true if ActivityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityType) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityType), nil
}

type LibraryType string

const (
	LibraryTypeMovie      LibraryType = "movie"
	LibraryTypeTvshow     LibraryType = "tvshow"
	LibraryTypeMusic      LibraryType = "music"
	LibraryTypeAudiobook  LibraryType = "audiobook"
	LibraryTypeBook       LibraryType = "book"
	LibraryTypePodcast    LibraryType = "podcast"
	LibraryTypePhoto      LibraryType = "photo"
	LibraryTypeLivetv     LibraryType = "livetv"
	LibraryTypeComics     LibraryType = "comics"
	LibraryTypeAdultMovie LibraryType = "adult_movie"
	LibraryTypeAdultScene LibraryType = "adult_scene"
)

func (e *LibraryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LibraryType(s)
	case string:
		*e = LibraryType(s)
	default:
		return fmt.Errorf("unsupported scan type for LibraryType: %T", src)
	}
	return nil
}

type NullLibraryType struct {
	LibraryType LibraryType `json:"libraryType"`
	Valid       bool        `json:"valid"` // Valid is true if LibraryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLibraryType) Scan(value interface{}) error {
	if value == nil {
		ns.LibraryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LibraryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLibraryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LibraryType), nil
}

type PermissionCategory string

const (
	PermissionCategorySystem    PermissionCategory = "system"
	PermissionCategoryUsers     PermissionCategory = "users"
	PermissionCategoryLibraries PermissionCategory = "libraries"
	PermissionCategoryContent   PermissionCategory = "content"
	PermissionCategoryPlayback  PermissionCategory = "playback"
	PermissionCategorySocial    PermissionCategory = "social"
	PermissionCategoryAdult     PermissionCategory = "adult"
)

func (e *PermissionCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionCategory(s)
	case string:
		*e = PermissionCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionCategory: %T", src)
	}
	return nil
}

type NullPermissionCategory struct {
	PermissionCategory PermissionCategory `json:"permissionCategory"`
	Valid              bool               `json:"valid"` // Valid is true if PermissionCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionCategory) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionCategory), nil
}

type RatingSystem string

const (
	RatingSystemMPAA       RatingSystem = "MPAA"
	RatingSystemFSK        RatingSystem = "FSK"
	RatingSystemPEGI       RatingSystem = "PEGI"
	RatingSystemBBFC       RatingSystem = "BBFC"
	RatingSystemACB        RatingSystem = "ACB"
	RatingSystemKIJKWIJZER RatingSystem = "KIJKWIJZER"
)

func (e *RatingSystem) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RatingSystem(s)
	case string:
		*e = RatingSystem(s)
	default:
		return fmt.Errorf("unsupported scan type for RatingSystem: %T", src)
	}
	return nil
}

type NullRatingSystem struct {
	RatingSystem RatingSystem `json:"ratingSystem"`
	Valid        bool         `json:"valid"` // Valid is true if RatingSystem is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRatingSystem) Scan(value interface{}) error {
	if value == nil {
		ns.RatingSystem, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RatingSystem.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRatingSystem) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RatingSystem), nil
}

type UserRole string

const (
	UserRoleAdmin     UserRole = "admin"
	UserRoleModerator UserRole = "moderator"
	UserRoleUser      UserRole = "user"
	UserRoleGuest     UserRole = "guest"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"userRole"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type ActivityLog struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"userId"`
	Type      string      `json:"type"`
	Severity  string      `json:"severity"`
	Message   string      `json:"message"`
	Metadata  []byte      `json:"metadata"`
	IpAddress netip.Addr  `json:"ipAddress"`
	UserAgent *string     `json:"userAgent"`
	CreatedAt time.Time   `json:"createdAt"`
}

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"userId"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"keyHash"`
	KeyPrefix  string             `json:"keyPrefix"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"lastUsedAt"`
	UseCount   int64              `json:"useCount"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt  time.Time          `json:"createdAt"`
}

type CGallery struct {
	ID        uuid.UUID   `json:"id"`
	MovieID   pgtype.UUID `json:"movieId"`
	Title     string      `json:"title"`
	Path      *string     `json:"path"`
	CreatedAt time.Time   `json:"createdAt"`
}

type CGalleryImage struct {
	ID        uuid.UUID   `json:"id"`
	GalleryID pgtype.UUID `json:"galleryId"`
	Path      string      `json:"path"`
	SortOrder int32       `json:"sortOrder"`
	CreatedAt time.Time   `json:"createdAt"`
}

type CMovie struct {
	ID            uuid.UUID   `json:"id"`
	LibraryID     uuid.UUID   `json:"libraryId"`
	WhisparrID    *int32      `json:"whisparrId"`
	StashdbID     *string     `json:"stashdbId"`
	TpdbID        *string     `json:"tpdbId"`
	Title         string      `json:"title"`
	SortTitle     *string     `json:"sortTitle"`
	OriginalTitle *string     `json:"originalTitle"`
	Overview      *string     `json:"overview"`
	ReleaseDate   pgtype.Date `json:"releaseDate"`
	RuntimeTicks  *int64      `json:"runtimeTicks"`
	StudioID      pgtype.UUID `json:"studioId"`
	Director      *string     `json:"director"`
	Series        *string     `json:"series"`
	Path          string      `json:"path"`
	SizeBytes     *int64      `json:"sizeBytes"`
	Container     *string     `json:"container"`
	VideoCodec    *string     `json:"videoCodec"`
	AudioCodec    *string     `json:"audioCodec"`
	Resolution    *string     `json:"resolution"`
	Phash         *string     `json:"phash"`
	Oshash        *string     `json:"oshash"`
	HasFile       *bool       `json:"hasFile"`
	IsHdr         *bool       `json:"isHdr"`
	Is3d          *bool       `json:"is3d"`
	CreatedAt     time.Time   `json:"createdAt"`
	UpdatedAt     time.Time   `json:"updatedAt"`
}

type CMovieImage struct {
	ID           uuid.UUID   `json:"id"`
	MovieID      pgtype.UUID `json:"movieId"`
	Type         string      `json:"type"`
	Path         string      `json:"path"`
	Source       *string     `json:"source"`
	PrimaryImage *bool       `json:"primaryImage"`
	CreatedAt    time.Time   `json:"createdAt"`
}

type CMoviePerformer struct {
	MovieID       uuid.UUID `json:"movieId"`
	PerformerID   uuid.UUID `json:"performerId"`
	CharacterName *string   `json:"characterName"`
}

type CMovieTag struct {
	MovieID uuid.UUID `json:"movieId"`
	TagID   uuid.UUID `json:"tagId"`
}

type CPerformer struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	Disambiguation *string     `json:"disambiguation"`
	Gender         *string     `json:"gender"`
	Birthdate      pgtype.Date `json:"birthdate"`
	DeathDate      pgtype.Date `json:"deathDate"`
	BirthCity      *string     `json:"birthCity"`
	Ethnicity      *string     `json:"ethnicity"`
	Nationality    *string     `json:"nationality"`
	HairColor      *string     `json:"hairColor"`
	EyeColor       *string     `json:"eyeColor"`
	HeightCm       *int32      `json:"heightCm"`
	WeightKg       *int32      `json:"weightKg"`
	Measurements   *string     `json:"measurements"`
	CupSize        *string     `json:"cupSize"`
	BreastType     *string     `json:"breastType"`
	Tattoos        *string     `json:"tattoos"`
	Piercings      *string     `json:"piercings"`
	CareerStart    *int32      `json:"careerStart"`
	CareerEnd      *int32      `json:"careerEnd"`
	Bio            *string     `json:"bio"`
	StashID        *string     `json:"stashId"`
	StashdbID      *string     `json:"stashdbId"`
	TpdbID         *string     `json:"tpdbId"`
	FreeonesID     *string     `json:"freeonesId"`
	Twitter        *string     `json:"twitter"`
	Instagram      *string     `json:"instagram"`
	ImagePath      *string     `json:"imagePath"`
	CreatedAt      time.Time   `json:"createdAt"`
	UpdatedAt      time.Time   `json:"updatedAt"`
}

type CPerformerAlias struct {
	PerformerID uuid.UUID `json:"performerId"`
	Alias       string    `json:"alias"`
}

type CPerformerImage struct {
	ID           uuid.UUID   `json:"id"`
	PerformerID  pgtype.UUID `json:"performerId"`
	Path         string      `json:"path"`
	Type         *string     `json:"type"`
	Source       *string     `json:"source"`
	PrimaryImage *bool       `json:"primaryImage"`
	CreatedAt    time.Time   `json:"createdAt"`
}

type CScene struct {
	ID             uuid.UUID   `json:"id"`
	LibraryID      uuid.UUID   `json:"libraryId"`
	Title          string      `json:"title"`
	SortTitle      *string     `json:"sortTitle"`
	Overview       *string     `json:"overview"`
	ReleaseDate    pgtype.Date `json:"releaseDate"`
	RuntimeMinutes *int32      `json:"runtimeMinutes"`
	StudioID       pgtype.UUID `json:"studioId"`
	WhisparrID     *int32      `json:"whisparrId"`
	StashID        *string     `json:"stashId"`
	StashdbID      *string     `json:"stashdbId"`
	TpdbID         *string     `json:"tpdbId"`
	Path           string      `json:"path"`
	SizeBytes      *int64      `json:"sizeBytes"`
	VideoCodec     *string     `json:"videoCodec"`
	AudioCodec     *string     `json:"audioCodec"`
	Resolution     *string     `json:"resolution"`
	Oshash         *string     `json:"oshash"`
	Phash          *string     `json:"phash"`
	Md5            *string     `json:"md5"`
	CoverPath      *string     `json:"coverPath"`
	CreatedAt      time.Time   `json:"createdAt"`
	UpdatedAt      time.Time   `json:"updatedAt"`
}

type CSceneMarker struct {
	ID            uuid.UUID   `json:"id"`
	SceneID       pgtype.UUID `json:"sceneId"`
	Title         *string     `json:"title"`
	StartSeconds  float64     `json:"startSeconds"`
	EndSeconds    *float64    `json:"endSeconds"`
	TagID         pgtype.UUID `json:"tagId"`
	StashMarkerID *string     `json:"stashMarkerId"`
	CreatedAt     time.Time   `json:"createdAt"`
}

type CScenePerformer struct {
	SceneID     uuid.UUID `json:"sceneId"`
	PerformerID uuid.UUID `json:"performerId"`
	Role        *string   `json:"role"`
}

type CSceneTag struct {
	SceneID uuid.UUID `json:"sceneId"`
	TagID   uuid.UUID `json:"tagId"`
}

type CStudio struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parentId"`
	StashdbID *string     `json:"stashdbId"`
	TpdbID    *string     `json:"tpdbId"`
	Url       *string     `json:"url"`
	LogoPath  *string     `json:"logoPath"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
}

type CTag struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	ParentID    pgtype.UUID `json:"parentId"`
	StashdbID   *string     `json:"stashdbId"`
	CreatedAt   time.Time   `json:"createdAt"`
}

type CUserFavorite struct {
	UserID    uuid.UUID `json:"userId"`
	MovieID   uuid.UUID `json:"movieId"`
	CreatedAt time.Time `json:"createdAt"`
}

type CUserPerformerFavorite struct {
	UserID      uuid.UUID `json:"userId"`
	PerformerID uuid.UUID `json:"performerId"`
	AddedAt     time.Time `json:"addedAt"`
}

type CUserRating struct {
	UserID    uuid.UUID `json:"userId"`
	MovieID   uuid.UUID `json:"movieId"`
	Rating    *int16    `json:"rating"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type CUserSceneDatum struct {
	UserID      uuid.UUID          `json:"userId"`
	SceneID     uuid.UUID          `json:"sceneId"`
	PositionMs  *int64             `json:"positionMs"`
	WatchCount  *int32             `json:"watchCount"`
	LastWatched pgtype.Timestamptz `json:"lastWatched"`
	Rating      *int16             `json:"rating"`
	OCounter    *int32             `json:"oCounter"`
	IsFavorite  *bool              `json:"isFavorite"`
	IsOrganized *bool              `json:"isOrganized"`
}

type CWatchHistory struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"userId"`
	MovieID       pgtype.UUID `json:"movieId"`
	WatchedAt     time.Time   `json:"watchedAt"`
	PositionTicks *int64      `json:"positionTicks"`
	Completed     *bool       `json:"completed"`
}

type ContentRating struct {
	ID          uuid.UUID    `json:"id"`
	System      RatingSystem `json:"system"`
	Code        string       `json:"code"`
	DisplayName string       `json:"displayName"`
	Description *string      `json:"description"`
	MinAge      *int32       `json:"minAge"`
	IconUrl     *string      `json:"iconUrl"`
	SortOrder   int32        `json:"sortOrder"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
}

type Genre struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Library struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Type              LibraryType        `json:"type"`
	Paths             []string           `json:"paths"`
	ScanEnabled       bool               `json:"scanEnabled"`
	ScanIntervalHours int32              `json:"scanIntervalHours"`
	LastScanAt        pgtype.Timestamptz `json:"lastScanAt"`
	LastScanDuration  pgtype.Interval    `json:"lastScanDuration"`
	PreferredLanguage *string            `json:"preferredLanguage"`
	DownloadImages    bool               `json:"downloadImages"`
	DownloadNfo       bool               `json:"downloadNfo"`
	GenerateChapters  bool               `json:"generateChapters"`
	IsPrivate         bool               `json:"isPrivate"`
	OwnerUserID       pgtype.UUID        `json:"ownerUserId"`
	SortOrder         int32              `json:"sortOrder"`
	Icon              *string            `json:"icon"`
	CreatedAt         time.Time          `json:"createdAt"`
	UpdatedAt         time.Time          `json:"updatedAt"`
}

type LibraryUserAccess struct {
	LibraryID uuid.UUID `json:"libraryId"`
	UserID    uuid.UUID `json:"userId"`
	CanManage bool      `json:"canManage"`
}

type OidcProvider struct {
	ID              uuid.UUID       `json:"id"`
	Name            string          `json:"name"`
	Slug            string          `json:"slug"`
	Enabled         bool            `json:"enabled"`
	IssuerUrl       string          `json:"issuerUrl"`
	ClientID        string          `json:"clientId"`
	ClientSecretEnc []byte          `json:"clientSecretEnc"`
	Scopes          []string        `json:"scopes"`
	ClaimMapping    json.RawMessage `json:"claimMapping"`
	RoleMapping     json.RawMessage `json:"roleMapping"`
	AutoProvision   bool            `json:"autoProvision"`
	DefaultRole     string          `json:"defaultRole"`
	CreatedAt       time.Time       `json:"createdAt"`
	UpdatedAt       time.Time       `json:"updatedAt"`
}

type OidcUserLink struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"userId"`
	ProviderID  uuid.UUID          `json:"providerId"`
	Subject     string             `json:"subject"`
	Email       *string            `json:"email"`
	Name        *string            `json:"name"`
	Groups      []string           `json:"groups"`
	LinkedAt    time.Time          `json:"linkedAt"`
	LastLoginAt pgtype.Timestamptz `json:"lastLoginAt"`
}

type Permission struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Category    string    `json:"category"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Profile struct {
	ID                        uuid.UUID `json:"id"`
	UserID                    uuid.UUID `json:"userId"`
	Name                      string    `json:"name"`
	AvatarUrl                 *string   `json:"avatarUrl"`
	IsDefault                 bool      `json:"isDefault"`
	IsKids                    bool      `json:"isKids"`
	MaxRatingLevel            int32     `json:"maxRatingLevel"`
	AdultEnabled              bool      `json:"adultEnabled"`
	PreferredLanguage         *string   `json:"preferredLanguage"`
	PreferredAudioLanguage    *string   `json:"preferredAudioLanguage"`
	PreferredSubtitleLanguage *string   `json:"preferredSubtitleLanguage"`
	AutoplayNext              *bool     `json:"autoplayNext"`
	AutoplayPreviews          *bool     `json:"autoplayPreviews"`
	CreatedAt                 time.Time `json:"createdAt"`
	UpdatedAt                 time.Time `json:"updatedAt"`
}

type RolePermission struct {
	Role         string `json:"role"`
	PermissionID int32  `json:"permissionId"`
}

type ServerSetting struct {
	Key         string          `json:"key"`
	Value       json.RawMessage `json:"value"`
	Category    string          `json:"category"`
	Description *string         `json:"description"`
	IsPublic    bool            `json:"isPublic"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

type Session struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"userId"`
	ProfileID     pgtype.UUID `json:"profileId"`
	TokenHash     string      `json:"tokenHash"`
	DeviceName    *string     `json:"deviceName"`
	DeviceType    *string     `json:"deviceType"`
	ClientName    *string     `json:"clientName"`
	ClientVersion *string     `json:"clientVersion"`
	IpAddress     netip.Addr  `json:"ipAddress"`
	UserAgent     *string     `json:"userAgent"`
	IsActive      bool        `json:"isActive"`
	LastActivity  time.Time   `json:"lastActivity"`
	ExpiresAt     time.Time   `json:"expiresAt"`
	CreatedAt     time.Time   `json:"createdAt"`
}

type User struct {
	ID                    uuid.UUID          `json:"id"`
	Username              string             `json:"username"`
	Email                 *string            `json:"email"`
	PasswordHash          *string            `json:"passwordHash"`
	IsAdmin               bool               `json:"isAdmin"`
	IsDisabled            bool               `json:"isDisabled"`
	MaxRatingLevel        int32              `json:"maxRatingLevel"`
	AdultEnabled          bool               `json:"adultEnabled"`
	PreferredLanguage     *string            `json:"preferredLanguage"`
	PreferredRatingSystem *string            `json:"preferredRatingSystem"`
	LastLoginAt           pgtype.Timestamptz `json:"lastLoginAt"`
	CreatedAt             time.Time          `json:"createdAt"`
	UpdatedAt             time.Time          `json:"updatedAt"`
	Role                  string             `json:"role"`
}
