DROP TABLE IF EXISTS c.user_scene_data;
DROP INDEX IF EXISTS idx_c_markers_scene;
DROP TABLE IF EXISTS c.scene_markers;
DROP TABLE IF EXISTS c.scene_tags;
DROP TABLE IF EXISTS c.scene_performers;
DROP TRIGGER IF EXISTS c_scenes_updated_at ON c.scenes;
DROP INDEX IF EXISTS idx_c_scenes_stashdb;
DROP INDEX IF EXISTS idx_c_scenes_oshash;
DROP INDEX IF EXISTS idx_c_scenes_studio;
DROP INDEX IF EXISTS idx_c_scenes_library;
DROP TABLE IF EXISTS c.scenes;
