DROP TABLE IF EXISTS c.user_performer_favorites;
DROP INDEX IF EXISTS idx_c_watch_history_user;
DROP TABLE IF EXISTS c.watch_history;
DROP TABLE IF EXISTS c.user_favorites;
DROP TRIGGER IF EXISTS c_user_ratings_updated_at ON c.user_ratings;
DROP TABLE IF EXISTS c.user_ratings;
DROP TABLE IF EXISTS c.gallery_images;
DROP TABLE IF EXISTS c.galleries;
DROP TABLE IF EXISTS c.movie_images;
DROP TABLE IF EXISTS c.movie_tags;
DROP TABLE IF EXISTS c.movie_performers;
DROP TRIGGER IF EXISTS c_movies_updated_at ON c.movies;
DROP INDEX IF EXISTS idx_c_movies_oshash;
DROP INDEX IF EXISTS idx_c_movies_phash;
DROP INDEX IF EXISTS idx_c_movies_studio;
DROP INDEX IF EXISTS idx_c_movies_library;
DROP TABLE IF EXISTS c.movies;
DROP TABLE IF EXISTS c.tags;
DROP TABLE IF EXISTS c.performer_images;
DROP TABLE IF EXISTS c.performer_aliases;
DROP TRIGGER IF EXISTS c_performers_updated_at ON c.performers;
DROP INDEX IF EXISTS idx_c_performers_stashdb;
DROP INDEX IF EXISTS idx_c_performers_name;
DROP TABLE IF EXISTS c.performers;
DROP TRIGGER IF EXISTS c_studios_updated_at ON c.studios;
DROP TABLE IF EXISTS c.studios;
