DROP TABLE IF EXISTS qar.user_performer_favorites;
DROP INDEX IF EXISTS idx_qar_watch_history_user;
DROP TABLE IF EXISTS qar.watch_history;
DROP TABLE IF EXISTS qar.user_favorites;
DROP TRIGGER IF EXISTS qar_user_ratings_updated_at ON qar.user_ratings;
DROP TABLE IF EXISTS qar.user_ratings;
DROP TABLE IF EXISTS qar.gallery_images;
DROP TABLE IF EXISTS qar.galleries;
DROP TABLE IF EXISTS qar.movie_images;
DROP TABLE IF EXISTS qar.movie_tags;
DROP TABLE IF EXISTS qar.movie_performers;
DROP TRIGGER IF EXISTS qar_movies_updated_at ON qar.movies;
DROP INDEX IF EXISTS idx_qar_movies_oshash;
DROP INDEX IF EXISTS idx_qar_movies_phash;
DROP INDEX IF EXISTS idx_qar_movies_studio;
DROP INDEX IF EXISTS idx_qar_movies_library;
DROP TABLE IF EXISTS qar.movies;
DROP TABLE IF EXISTS qar.tags;
DROP TABLE IF EXISTS qar.performer_images;
DROP TABLE IF EXISTS qar.performer_aliases;
DROP TRIGGER IF EXISTS qar_performers_updated_at ON qar.performers;
DROP INDEX IF EXISTS idx_qar_performers_stashdb;
DROP INDEX IF EXISTS idx_qar_performers_name;
DROP TABLE IF EXISTS qar.performers;
DROP TRIGGER IF EXISTS qar_studios_updated_at ON qar.studios;
DROP TABLE IF EXISTS qar.studios;
