// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveSessionsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountLibraries(ctx context.Context) (int64, error)
	CountProfilesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// Activity Log
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error)
	CreateOIDCLink(ctx context.Context, arg CreateOIDCLinkParams) (OidcUserLink, error)
	CreateOIDCProvider(ctx context.Context, arg CreateOIDCProviderParams) (OidcProvider, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateSession(ctx context.Context, id uuid.UUID) error
	DeactivateUserSessions(ctx context.Context, userID uuid.UUID) error
	DeleteAPIKey(ctx context.Context, id uuid.UUID) error
	DeleteExpiredAPIKeys(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteLibrary(ctx context.Context, id uuid.UUID) error
	DeleteOIDCLink(ctx context.Context, id uuid.UUID) error
	DeleteOIDCLinksByProvider(ctx context.Context, providerID uuid.UUID) error
	DeleteOIDCLinksByUser(ctx context.Context, userID uuid.UUID) error
	DeleteOIDCProvider(ctx context.Context, id uuid.UUID) error
	DeleteOldActivityLogs(ctx context.Context, createdAt time.Time) error
	DeleteProfile(ctx context.Context, id uuid.UUID) error
	DeleteServerSetting(ctx context.Context, key string) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) ([]ApiKey, error)
	GetDefaultProfile(ctx context.Context, userID uuid.UUID) (Profile, error)
	GetLibraryByID(ctx context.Context, id uuid.UUID) (Library, error)
	// OIDC User Links
	GetOIDCLinkByID(ctx context.Context, id uuid.UUID) (OidcUserLink, error)
	GetOIDCLinkBySubject(ctx context.Context, arg GetOIDCLinkBySubjectParams) (OidcUserLink, error)
	// OIDC Providers
	GetOIDCProviderByID(ctx context.Context, id uuid.UUID) (OidcProvider, error)
	GetOIDCProviderBySlug(ctx context.Context, slug string) (OidcProvider, error)
	GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error)
	// Server Settings
	GetServerSetting(ctx context.Context, key string) (ServerSetting, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Library User Access
	GrantLibraryAccess(ctx context.Context, arg GrantLibraryAccessParams) error
	ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error)
	ListAccessibleLibraries(ctx context.Context, ownerUserID pgtype.UUID) ([]Library, error)
	ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]Session, error)
	ListActivityLogByAction(ctx context.Context, arg ListActivityLogByActionParams) ([]ActivityLog, error)
	ListActivityLogByModule(ctx context.Context, arg ListActivityLogByModuleParams) ([]ActivityLog, error)
	ListActivityLogByUser(ctx context.Context, arg ListActivityLogByUserParams) ([]ActivityLog, error)
	ListEnabledOIDCProviders(ctx context.Context) ([]OidcProvider, error)
	ListLibraries(ctx context.Context) ([]Library, error)
	ListLibrariesByType(ctx context.Context, type_ LibraryType) ([]Library, error)
	ListLibraryUsers(ctx context.Context, libraryID uuid.UUID) ([]ListLibraryUsersRow, error)
	ListOIDCLinksByUser(ctx context.Context, userID uuid.UUID) ([]ListOIDCLinksByUserRow, error)
	ListOIDCProviders(ctx context.Context) ([]OidcProvider, error)
	ListProfilesByUser(ctx context.Context, userID uuid.UUID) ([]Profile, error)
	ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]ActivityLog, error)
	ListServerSettings(ctx context.Context) ([]ServerSetting, error)
	ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RevokeLibraryAccess(ctx context.Context, arg RevokeLibraryAccessParams) error
	SetDefaultProfile(ctx context.Context, arg SetDefaultProfileParams) error
	UpdateAPIKeyUsage(ctx context.Context, id uuid.UUID) error
	UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error)
	UpdateLibraryScanStatus(ctx context.Context, arg UpdateLibraryScanStatusParams) error
	UpdateOIDCLinkLogin(ctx context.Context, arg UpdateOIDCLinkLoginParams) error
	UpdateOIDCProvider(ctx context.Context, arg UpdateOIDCProviderParams) (OidcProvider, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpsertServerSetting(ctx context.Context, arg UpsertServerSettingParams) (ServerSetting, error)
	UserCanAccessLibrary(ctx context.Context, arg UserCanAccessLibraryParams) (bool, error)
	UserExistsByEmail(ctx context.Context, email *string) (bool, error)
	UserExistsByUsername(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
